# Generated by Django 4.2.16 on 2024-12-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(help_text='Example:xyz_01@gmail.com', max_length=254)),
                ('address', models.TextField()),
                ('age', models.IntegerField()),
                ('pno', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Customer Details',
            },
        ),
    ]
